#!/bin/bash
ls >> lsOutput.log
cd new
magick mogrify -format jpeg -quality 80 *.jpeg
cp *.jpeg o
magick mogrify -resize 800 -quality 80 *.jpeg
cp *.jpeg 800
magick mogrify -resize 400 -quality 80 *.jpeg
cp *.jpeg 400
magick mogrify -resize 200 -quality 80 *.jpeg
cp *.jpeg 200